python-docker: fix pyproject.toml issues
* Getting build dependencies for wheel...

ERROR Missing dependencies:
   hatch-vcs

File "./staging_dir/hostpkg/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 51, in validate
raise ValueError(f"{error}\n{summary}") from None
ValueError: invalid pyproject.toml config: `project.license`.
configuration error: `project.license` must be valid exactly by one definition (2 matches found):

- keys:
    'file': {type: string}
  required: ['file']
- keys:
    'text': {type: string}
  required: ['text']

Signed-off-by: Javier Marcet <javier@marcet.info>